apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  label:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: nginx