apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - mountPath: "/var/www/html"
      name: html-store
  volumes:
    - name: html-store
      persistentVolumeClaim:
        claimName: local-pvc
# /var/lib/docker/volumes/minikube/_data/data/vol1/ on the host
# https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
# sudo ln -s /var/lib/docker/volumes/minikube/_data/data /data