apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/vol1
# /var/lib/docker/volumes/minikube/_data/data/vol1/ on the host
# https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
# sudo ln -s /var/lib/docker/volumes/minikube/_data/data /data