apiVersion: v1
kind: Pod
metadata:
  name: purple
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.34
    name: purple-container
  initContainers:
  - command:
    - sh
    - -c
    - sleep 60
    image: busybox:1.34
    name: warm-up-1
  - command:
    - sh
    - -c
    - sleep 120
    image: busybox:1.34
    name: warm-up-2