apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:1.19.1
    name: nginx
    volumeMounts:
      - name: nginx-config-volume
        mountPath: /etc/nginx
      - name: secret-config-volume
        mountPath: /etc/nginx/conf/
    ports:
    - containerPort: 80
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: secret-config-volume
    secret:
      secretName: nginx-htpasswd