apiVersion: v1
kind: Config

current-context: kube-admin@kube-master

clusters:
  - name: kube-master
    cluster:
      certificate-authority: /full/path/ca.crt
      #certificate-authority-data: base64 encoded cert goes here instead of the path specified above in "certificate-authority"
      server: https://kube-master:6443

contexts:
- name: kube-admin@kube-master
  context:
    cluster: kube-master
    user: kube-admin
    namespace: default

users:
  - name: kube-admin
    user:
      client-certificate: /full/path/admin.crt
      client-key: /full/path/admin.key