apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  awsElasticBlockStore:
    volumeID: #<volume-id>
    fsType: ext4