apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: #<volume-id>
    fsType: ext4