apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
- apiGroups:
  - ""
  resources:
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "storageclasses"
  verbs:
  - "*"

#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
#  name: storage-admin
#rules:
#- apiGroups: [""]
#  resources: ["persistentvolumes"]
#  verbs: ["create", "delete", "deletecollection" ,"get", "list", "patch", "update", "watch"]
#- apiGroups: ["storage.k8s.io/v1"]
#  resources: ["storageclasses"]
#  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]