apiVersion: v1
kind: Pod
metadata:
  name: multi-pods
spec:
  securityContext:
    runAsUser: 1000
  containers:
  -  image: nginx
     name: web
     command: ["sleep", "4000"]
     securityContext:
      runAsUser: 1010

  -  image: alpine
     name: sidecar
     command: ["sleep", "4000"]