apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-2
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu
    securityContext:
      runAsUser: 1010
      capabilities:
        add: ["SYS_TIME","NET_ADMIN"]
  securityContext:
    runAsUser: 1010